// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package testserver;

public final class TestServerImplementation_Stub
    extends java.rmi.server.RemoteStub
    implements testserver.TestServerInterface, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_createProcessUtil_0;
    private static java.lang.reflect.Method $method_getAuditTrail_1;
    private static java.lang.reflect.Method $method_getProcessInstancesIDs_2;
    private static java.lang.reflect.Method $method_getTaskList_3;
    private static java.lang.reflect.Method $method_initTaskList_4;
    private static java.lang.reflect.Method $method_invokeASynchronousOneWayService_5;
    private static java.lang.reflect.Method $method_invokeASynchronousTwoWayService_6;
    private static java.lang.reflect.Method $method_invokeSynchronousService_7;
    private static java.lang.reflect.Method $method_invokeSynchronousService_8;
    private static java.lang.reflect.Method $method_raiseBusinessEvent_9;
    private static java.lang.reflect.Method $method_resetHumanWorkFlowInteraction_10;
    private static java.lang.reflect.Method $method_resetProcessUtil_11;
    private static java.lang.reflect.Method $method_stopTestServer_12;
    private static java.lang.reflect.Method $method_updateTaskOutcome_13;
    
    static {
	try {
	    $method_createProcessUtil_0 = testserver.TestServerInterface.class.getMethod("createProcessUtil", new java.lang.Class[] {boolean.class, java.lang.String.class});
	    $method_getAuditTrail_1 = testserver.TestServerInterface.class.getMethod("getAuditTrail", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	    $method_getProcessInstancesIDs_2 = testserver.TestServerInterface.class.getMethod("getProcessInstancesIDs", new java.lang.Class[] {java.lang.String.class});
	    $method_getTaskList_3 = testserver.TestServerInterface.class.getMethod("getTaskList", new java.lang.Class[] {});
	    $method_initTaskList_4 = testserver.TestServerInterface.class.getMethod("initTaskList", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, boolean.class});
	    $method_invokeASynchronousOneWayService_5 = testserver.TestServerInterface.class.getMethod("invokeASynchronousOneWayService", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, boolean.class});
	    $method_invokeASynchronousTwoWayService_6 = testserver.TestServerInterface.class.getMethod("invokeASynchronousTwoWayService", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, boolean.class});
	    $method_invokeSynchronousService_7 = testserver.TestServerInterface.class.getMethod("invokeSynchronousService", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, boolean.class});
	    $method_invokeSynchronousService_8 = testserver.TestServerInterface.class.getMethod("invokeSynchronousService", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, boolean.class});
	    $method_raiseBusinessEvent_9 = testserver.TestServerInterface.class.getMethod("raiseBusinessEvent", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, boolean.class});
	    $method_resetHumanWorkFlowInteraction_10 = testserver.TestServerInterface.class.getMethod("resetHumanWorkFlowInteraction", new java.lang.Class[] {});
	    $method_resetProcessUtil_11 = testserver.TestServerInterface.class.getMethod("resetProcessUtil", new java.lang.Class[] {});
	    $method_stopTestServer_12 = testserver.TestServerInterface.class.getMethod("stopTestServer", new java.lang.Class[] {});
	    $method_updateTaskOutcome_13 = testserver.TestServerInterface.class.getMethod("updateTaskOutcome", new java.lang.Class[] {java.lang.String.class, java.lang.String.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public TestServerImplementation_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of createProcessUtil(boolean, String)
    public void createProcessUtil(boolean $param_boolean_1, java.lang.String $param_String_2)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	ref.invoke(this, $method_createProcessUtil_0, new java.lang.Object[] {($param_boolean_1 ? java.lang.Boolean.TRUE : java.lang.Boolean.FALSE), $param_String_2}, -7804633490379691369L);
    }
    
    // implementation of getAuditTrail(String, String)
    public java.lang.String getAuditTrail(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_getAuditTrail_1, new java.lang.Object[] {$param_String_1, $param_String_2}, 3941487459200516901L);
	return ((java.lang.String) $result);
    }
    
    // implementation of getProcessInstancesIDs(String)
    public java.lang.String[] getProcessInstancesIDs(java.lang.String $param_String_1)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_getProcessInstancesIDs_2, new java.lang.Object[] {$param_String_1}, -8800825448510309306L);
	return ((java.lang.String[]) $result);
    }
    
    // implementation of getTaskList()
    public java.lang.String[] getTaskList()
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_getTaskList_3, null, -6550228864999099725L);
	return ((java.lang.String[]) $result);
    }
    
    // implementation of initTaskList(String, String, boolean)
    public void initTaskList(java.lang.String $param_String_1, java.lang.String $param_String_2, boolean $param_boolean_3)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	ref.invoke(this, $method_initTaskList_4, new java.lang.Object[] {$param_String_1, $param_String_2, ($param_boolean_3 ? java.lang.Boolean.TRUE : java.lang.Boolean.FALSE)}, 4959525892998735743L);
    }
    
    // implementation of invokeASynchronousOneWayService(String, String, boolean)
    public java.lang.String invokeASynchronousOneWayService(java.lang.String $param_String_1, java.lang.String $param_String_2, boolean $param_boolean_3)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_invokeASynchronousOneWayService_5, new java.lang.Object[] {$param_String_1, $param_String_2, ($param_boolean_3 ? java.lang.Boolean.TRUE : java.lang.Boolean.FALSE)}, 216488616941214199L);
	return ((java.lang.String) $result);
    }
    
    // implementation of invokeASynchronousTwoWayService(String, String, boolean)
    public java.lang.String invokeASynchronousTwoWayService(java.lang.String $param_String_1, java.lang.String $param_String_2, boolean $param_boolean_3)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_invokeASynchronousTwoWayService_6, new java.lang.Object[] {$param_String_1, $param_String_2, ($param_boolean_3 ? java.lang.Boolean.TRUE : java.lang.Boolean.FALSE)}, 6519014886454051397L);
	return ((java.lang.String) $result);
    }
    
    // implementation of invokeSynchronousService(String, String, String, String, String, String, boolean)
    public java.lang.String invokeSynchronousService(java.lang.String $param_String_1, java.lang.String $param_String_2, java.lang.String $param_String_3, java.lang.String $param_String_4, java.lang.String $param_String_5, java.lang.String $param_String_6, boolean $param_boolean_7)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_invokeSynchronousService_7, new java.lang.Object[] {$param_String_1, $param_String_2, $param_String_3, $param_String_4, $param_String_5, $param_String_6, ($param_boolean_7 ? java.lang.Boolean.TRUE : java.lang.Boolean.FALSE)}, 6461389084958157837L);
	return ((java.lang.String) $result);
    }
    
    // implementation of invokeSynchronousService(String, String, boolean)
    public java.lang.String invokeSynchronousService(java.lang.String $param_String_1, java.lang.String $param_String_2, boolean $param_boolean_3)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_invokeSynchronousService_8, new java.lang.Object[] {$param_String_1, $param_String_2, ($param_boolean_3 ? java.lang.Boolean.TRUE : java.lang.Boolean.FALSE)}, -1992921373295902069L);
	return ((java.lang.String) $result);
    }
    
    // implementation of raiseBusinessEvent(String, String, boolean)
    public void raiseBusinessEvent(java.lang.String $param_String_1, java.lang.String $param_String_2, boolean $param_boolean_3)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	ref.invoke(this, $method_raiseBusinessEvent_9, new java.lang.Object[] {$param_String_1, $param_String_2, ($param_boolean_3 ? java.lang.Boolean.TRUE : java.lang.Boolean.FALSE)}, -7760559039085633470L);
    }
    
    // implementation of resetHumanWorkFlowInteraction()
    public void resetHumanWorkFlowInteraction()
	throws java.lang.Exception, java.rmi.RemoteException
    {
	ref.invoke(this, $method_resetHumanWorkFlowInteraction_10, null, 575178964718319503L);
    }
    
    // implementation of resetProcessUtil()
    public void resetProcessUtil()
	throws java.lang.Exception, java.rmi.RemoteException
    {
	ref.invoke(this, $method_resetProcessUtil_11, null, -4471546117463887999L);
    }
    
    // implementation of stopTestServer()
    public void stopTestServer()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_stopTestServer_12, null, -855628000042350941L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of updateTaskOutcome(String, String)
    public java.lang.String updateTaskOutcome(java.lang.String $param_String_1, java.lang.String $param_String_2)
	throws java.lang.Exception, java.rmi.RemoteException
    {
	Object $result = ref.invoke(this, $method_updateTaskOutcome_13, new java.lang.Object[] {$param_String_1, $param_String_2}, -2940019042496545953L);
	return ((java.lang.String) $result);
    }
}
