//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 12:41:40 PM CET 
//


package com.carlgira.oracle.bpel.test.model.composite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://xmlns.oracle.com/sca/1.0}implementation.mediator"/>
 *         &lt;element ref="{http://xmlns.oracle.com/sca/1.0}implementation.workflow"/>
 *         &lt;element ref="{http://xmlns.oracle.com/sca/1.0}implementation.bpel"/>
 *       &lt;/choice>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "implementationMediator",
    "implementationWorkflow",
    "implementationBpel"
})
@XmlRootElement(name = "component")
public class Component {

    @XmlElement(name = "implementation.mediator")
    protected ImplementationMediator implementationMediator;
    @XmlElement(name = "implementation.workflow")
    protected ImplementationWorkflow implementationWorkflow;
    @XmlElement(name = "implementation.bpel")
    protected ImplementationBpel implementationBpel;
    @XmlAttribute(name = "name", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String name;

    /**
     * Gets the value of the implementationMediator property.
     * 
     * @return
     *     possible object is
     *     {@link ImplementationMediator }
     *     
     */
    public ImplementationMediator getImplementationMediator() {
        return implementationMediator;
    }

    /**
     * Sets the value of the implementationMediator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImplementationMediator }
     *     
     */
    public void setImplementationMediator(ImplementationMediator value) {
        this.implementationMediator = value;
    }

    /**
     * Gets the value of the implementationWorkflow property.
     * 
     * @return
     *     possible object is
     *     {@link ImplementationWorkflow }
     *     
     */
    public ImplementationWorkflow getImplementationWorkflow() {
        return implementationWorkflow;
    }

    /**
     * Sets the value of the implementationWorkflow property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImplementationWorkflow }
     *     
     */
    public void setImplementationWorkflow(ImplementationWorkflow value) {
        this.implementationWorkflow = value;
    }

    /**
     * Gets the value of the implementationBpel property.
     * 
     * @return
     *     possible object is
     *     {@link ImplementationBpel }
     *     
     */
    public ImplementationBpel getImplementationBpel() {
        return implementationBpel;
    }

    /**
     * Sets the value of the implementationBpel property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImplementationBpel }
     *     
     */
    public void setImplementationBpel(ImplementationBpel value) {
        this.implementationBpel = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
