//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 12:41:40 PM CET 
//


package com.carlgira.oracle.bpel.test.model.composite;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.carlgira.oracle.bpel.test.model.composite package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SourceUri_QNAME = new QName("http://xmlns.oracle.com/sca/1.0", "source.uri");
    private final static QName _TargetUri_QNAME = new QName("http://xmlns.oracle.com/sca/1.0", "target.uri");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.carlgira.oracle.bpel.test.model.composite
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Wire }
     * 
     */
    public Wire createWire() {
        return new Wire();
    }

    /**
     * Create an instance of {@link BindingWs }
     * 
     */
    public BindingWs createBindingWs() {
        return new BindingWs();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link BindingJca }
     * 
     */
    public BindingJca createBindingJca() {
        return new BindingJca();
    }

    /**
     * Create an instance of {@link InterfaceWsdl }
     * 
     */
    public InterfaceWsdl createInterfaceWsdl() {
        return new InterfaceWsdl();
    }

    /**
     * Create an instance of {@link Composite }
     * 
     */
    public Composite createComposite() {
        return new Composite();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Service }
     * 
     */
    public Service createService() {
        return new Service();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link ImplementationMediator }
     * 
     */
    public ImplementationMediator createImplementationMediator() {
        return new ImplementationMediator();
    }

    /**
     * Create an instance of {@link ImplementationWorkflow }
     * 
     */
    public ImplementationWorkflow createImplementationWorkflow() {
        return new ImplementationWorkflow();
    }

    /**
     * Create an instance of {@link ImplementationBpel }
     * 
     */
    public ImplementationBpel createImplementationBpel() {
        return new ImplementationBpel();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/sca/1.0", name = "source.uri")
    public JAXBElement<String> createSourceUri(String value) {
        return new JAXBElement<String>(_SourceUri_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.oracle.com/sca/1.0", name = "target.uri")
    public JAXBElement<String> createTargetUri(String value) {
        return new JAXBElement<String>(_TargetUri_QNAME, String.class, null, value);
    }

}
