//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.02 at 12:41:40 PM CET 
//


package com.carlgira.oracle.bpel.test.model.composite;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/sca/1.0}source.uri"/>
 *         &lt;element ref="{http://xmlns.oracle.com/sca/1.0}target.uri"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sourceUri",
    "targetUri"
})
@XmlRootElement(name = "wire")
public class Wire {

    @XmlElement(name = "source.uri", required = true)
    protected String sourceUri;
    @XmlElement(name = "target.uri", required = true)
    protected String targetUri;

    /**
     * Gets the value of the sourceUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceUri() {
        return sourceUri;
    }

    /**
     * Sets the value of the sourceUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceUri(String value) {
        this.sourceUri = value;
    }

    /**
     * Gets the value of the targetUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetUri() {
        return targetUri;
    }

    /**
     * Sets the value of the targetUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetUri(String value) {
        this.targetUri = value;
    }

}
