//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 01:53:07 PM CET 
//


package com.carlgira.oracle.bpel.test.model.task;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}applicationContext"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}taskOwner"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}expirationDuration"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}sharePayloadConfiguration"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "applicationContext",
    "taskOwner",
    "expirationDuration",
    "sharePayloadConfiguration"
})
@XmlRootElement(name = "globalConfiguration")
public class GlobalConfiguration {

    @XmlElement(required = true)
    protected ApplicationContext applicationContext;
    @XmlElement(required = true)
    protected TaskOwner taskOwner;
    @XmlElement(required = true)
    protected ExpirationDuration expirationDuration;
    @XmlElement(required = true)
    protected SharePayloadConfiguration sharePayloadConfiguration;

    /**
     * Gets the value of the applicationContext property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationContext }
     *     
     */
    public ApplicationContext getApplicationContext() {
        return applicationContext;
    }

    /**
     * Sets the value of the applicationContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationContext }
     *     
     */
    public void setApplicationContext(ApplicationContext value) {
        this.applicationContext = value;
    }

    /**
     * Gets the value of the taskOwner property.
     * 
     * @return
     *     possible object is
     *     {@link TaskOwner }
     *     
     */
    public TaskOwner getTaskOwner() {
        return taskOwner;
    }

    /**
     * Sets the value of the taskOwner property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskOwner }
     *     
     */
    public void setTaskOwner(TaskOwner value) {
        this.taskOwner = value;
    }

    /**
     * Gets the value of the expirationDuration property.
     * 
     * @return
     *     possible object is
     *     {@link ExpirationDuration }
     *     
     */
    public ExpirationDuration getExpirationDuration() {
        return expirationDuration;
    }

    /**
     * Sets the value of the expirationDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpirationDuration }
     *     
     */
    public void setExpirationDuration(ExpirationDuration value) {
        this.expirationDuration = value;
    }

    /**
     * Gets the value of the sharePayloadConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link SharePayloadConfiguration }
     *     
     */
    public SharePayloadConfiguration getSharePayloadConfiguration() {
        return sharePayloadConfiguration;
    }

    /**
     * Sets the value of the sharePayloadConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link SharePayloadConfiguration }
     *     
     */
    public void setSharePayloadConfiguration(SharePayloadConfiguration value) {
        this.sharePayloadConfiguration = value;
    }

}
