//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 01:53:07 PM CET 
//


package com.carlgira.oracle.bpel.test.model.task;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}reminder"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}groupNotificationConfiguration"/>
 *       &lt;/sequence>
 *       &lt;attribute name="actionable" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="hideWorklistUrlInEmail" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="includeTaskAttachments" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="oneNotificationPerUserPerAction" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="secureNotifications" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reminder",
    "groupNotificationConfiguration"
})
@XmlRootElement(name = "notification")
public class Notification {

    @XmlElement(required = true)
    protected Reminder reminder;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String groupNotificationConfiguration;
    @XmlAttribute(name = "actionable", required = true)
    protected boolean actionable;
    @XmlAttribute(name = "hideWorklistUrlInEmail", required = true)
    protected boolean hideWorklistUrlInEmail;
    @XmlAttribute(name = "includeTaskAttachments", required = true)
    protected boolean includeTaskAttachments;
    @XmlAttribute(name = "oneNotificationPerUserPerAction", required = true)
    protected boolean oneNotificationPerUserPerAction;
    @XmlAttribute(name = "secureNotifications", required = true)
    protected boolean secureNotifications;

    /**
     * Gets the value of the reminder property.
     * 
     * @return
     *     possible object is
     *     {@link Reminder }
     *     
     */
    public Reminder getReminder() {
        return reminder;
    }

    /**
     * Sets the value of the reminder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reminder }
     *     
     */
    public void setReminder(Reminder value) {
        this.reminder = value;
    }

    /**
     * Gets the value of the groupNotificationConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupNotificationConfiguration() {
        return groupNotificationConfiguration;
    }

    /**
     * Sets the value of the groupNotificationConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupNotificationConfiguration(String value) {
        this.groupNotificationConfiguration = value;
    }

    /**
     * Gets the value of the actionable property.
     * 
     */
    public boolean isActionable() {
        return actionable;
    }

    /**
     * Sets the value of the actionable property.
     * 
     */
    public void setActionable(boolean value) {
        this.actionable = value;
    }

    /**
     * Gets the value of the hideWorklistUrlInEmail property.
     * 
     */
    public boolean isHideWorklistUrlInEmail() {
        return hideWorklistUrlInEmail;
    }

    /**
     * Sets the value of the hideWorklistUrlInEmail property.
     * 
     */
    public void setHideWorklistUrlInEmail(boolean value) {
        this.hideWorklistUrlInEmail = value;
    }

    /**
     * Gets the value of the includeTaskAttachments property.
     * 
     */
    public boolean isIncludeTaskAttachments() {
        return includeTaskAttachments;
    }

    /**
     * Sets the value of the includeTaskAttachments property.
     * 
     */
    public void setIncludeTaskAttachments(boolean value) {
        this.includeTaskAttachments = value;
    }

    /**
     * Gets the value of the oneNotificationPerUserPerAction property.
     * 
     */
    public boolean isOneNotificationPerUserPerAction() {
        return oneNotificationPerUserPerAction;
    }

    /**
     * Sets the value of the oneNotificationPerUserPerAction property.
     * 
     */
    public void setOneNotificationPerUserPerAction(boolean value) {
        this.oneNotificationPerUserPerAction = value;
    }

    /**
     * Gets the value of the secureNotifications property.
     * 
     */
    public boolean isSecureNotifications() {
        return secureNotifications;
    }

    /**
     * Sets the value of the secureNotifications property.
     * 
     */
    public void setSecureNotifications(boolean value) {
        this.secureNotifications = value;
    }

}
