//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 01:53:07 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.oracle.com/bpel/workflow/routingSlip", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.carlgira.oracle.bpel.test.model.task;
