//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 01:53:07 PM CET 
//


package com.carlgira.oracle.bpel.test.model.task;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}stage"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isAdhocRoutingSupported" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stage"
})
@XmlRootElement(name = "participants")
public class Participants {

    @XmlElement(required = true)
    protected Stage stage;
    @XmlAttribute(name = "isAdhocRoutingSupported", required = true)
    protected boolean isAdhocRoutingSupported;

    /**
     * Gets the value of the stage property.
     * 
     * @return
     *     possible object is
     *     {@link Stage }
     *     
     */
    public Stage getStage() {
        return stage;
    }

    /**
     * Sets the value of the stage property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stage }
     *     
     */
    public void setStage(Stage value) {
        this.stage = value;
    }

    /**
     * Gets the value of the isAdhocRoutingSupported property.
     * 
     */
    public boolean isIsAdhocRoutingSupported() {
        return isAdhocRoutingSupported;
    }

    /**
     * Sets the value of the isAdhocRoutingSupported property.
     * 
     */
    public void setIsAdhocRoutingSupported(boolean value) {
        this.isAdhocRoutingSupported = value;
    }

}
