//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 01:53:07 PM CET 
//


package com.carlgira.oracle.bpel.test.model.task;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}messageAttribute" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="externalSchema" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="xmlSchemaDefinition" use="required" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageAttribute"
})
@XmlRootElement(name = "payload", namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
public class Payload {

    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    protected List<MessageAttribute> messageAttribute;
    @XmlAttribute(name = "externalSchema", required = true)
    protected boolean externalSchema;
    @XmlAttribute(name = "xmlSchemaDefinition", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String xmlSchemaDefinition;

    /**
     * Gets the value of the messageAttribute property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messageAttribute property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessageAttribute().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageAttribute }
     * 
     * 
     */
    public List<MessageAttribute> getMessageAttribute() {
        if (messageAttribute == null) {
            messageAttribute = new ArrayList<MessageAttribute>();
        }
        return this.messageAttribute;
    }

    /**
     * Gets the value of the externalSchema property.
     * 
     */
    public boolean isExternalSchema() {
        return externalSchema;
    }

    /**
     * Sets the value of the externalSchema property.
     * 
     */
    public void setExternalSchema(boolean value) {
        this.externalSchema = value;
    }

    /**
     * Gets the value of the xmlSchemaDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlSchemaDefinition() {
        return xmlSchemaDefinition;
    }

    /**
     * Sets the value of the xmlSchemaDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlSchemaDefinition(String value) {
        this.xmlSchemaDefinition = value;
    }

}
