//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 01:53:07 PM CET 
//


package com.carlgira.oracle.bpel.test.model.task;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}globalConfiguration"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}participants"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}onErrorParticipant"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/routingSlip}notification"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalConfiguration",
    "participants",
    "onErrorParticipant",
    "notification"
})
@XmlRootElement(name = "routingSlip")
public class RoutingSlip {

    @XmlElement(required = true)
    protected GlobalConfiguration globalConfiguration;
    @XmlElement(required = true)
    protected Participants participants;
    @XmlElement(required = true)
    protected Resource onErrorParticipant;
    @XmlElement(required = true)
    protected Notification notification;

    /**
     * Gets the value of the globalConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalConfiguration }
     *     
     */
    public GlobalConfiguration getGlobalConfiguration() {
        return globalConfiguration;
    }

    /**
     * Sets the value of the globalConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalConfiguration }
     *     
     */
    public void setGlobalConfiguration(GlobalConfiguration value) {
        this.globalConfiguration = value;
    }

    /**
     * Gets the value of the participants property.
     * 
     * @return
     *     possible object is
     *     {@link Participants }
     *     
     */
    public Participants getParticipants() {
        return participants;
    }

    /**
     * Sets the value of the participants property.
     * 
     * @param value
     *     allowed object is
     *     {@link Participants }
     *     
     */
    public void setParticipants(Participants value) {
        this.participants = value;
    }

    /**
     * Gets the value of the onErrorParticipant property.
     * 
     * @return
     *     possible object is
     *     {@link Resource }
     *     
     */
    public Resource getOnErrorParticipant() {
        return onErrorParticipant;
    }

    /**
     * Sets the value of the onErrorParticipant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Resource }
     *     
     */
    public void setOnErrorParticipant(Resource value) {
        this.onErrorParticipant = value;
    }

    /**
     * Gets the value of the notification property.
     * 
     * @return
     *     possible object is
     *     {@link Notification }
     *     
     */
    public Notification getNotification() {
        return notification;
    }

    /**
     * Sets the value of the notification property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notification }
     *     
     */
    public void setNotification(Notification value) {
        this.notification = value;
    }

}
