//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.29 at 01:53:07 PM CET 
//


package com.carlgira.oracle.bpel.test.model.task;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}outcomes"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}restrictedActions"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}payload"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}bpelEventListener"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}bpelNoCallbacks"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}showCompleteGraphicalHistory"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}reevalTranslatablesOnUpdate"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}preActionMandatoryUserSteps"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}allowInitiatorEditParticipants"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}allowParticipantsEditParticipants"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}globalCreationTask"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}taskFlowFileLocation"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}workflowConditions"/>
 *         &lt;element ref="{http://xmlns.oracle.com/bpel/workflow/configuration}taskSequenceTypes" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outcomes",
    "restrictedActions",
    "payload",
    "bpelEventListener",
    "bpelNoCallbacks",
    "showCompleteGraphicalHistory",
    "reevalTranslatablesOnUpdate",
    "preActionMandatoryUserSteps",
    "allowInitiatorEditParticipants",
    "allowParticipantsEditParticipants",
    "globalCreationTask",
    "taskFlowFileLocation",
    "workflowConditions",
    "taskSequenceTypes"
})
@XmlRootElement(name = "workflowConfiguration", namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
public class WorkflowConfiguration {

    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    protected Outcomes outcomes;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    protected RestrictedActions restrictedActions;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    protected Payload payload;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
    protected boolean bpelEventListener;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
    protected boolean bpelNoCallbacks;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
    protected boolean showCompleteGraphicalHistory;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
    protected boolean reevalTranslatablesOnUpdate;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    protected PreActionMandatoryUserSteps preActionMandatoryUserSteps;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
    protected boolean allowInitiatorEditParticipants;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
    protected boolean allowParticipantsEditParticipants;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration")
    protected boolean globalCreationTask;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String taskFlowFileLocation;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    protected WorkflowConditions workflowConditions;
    @XmlElement(namespace = "http://xmlns.oracle.com/bpel/workflow/configuration", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected List<String> taskSequenceTypes;

    /**
     * Gets the value of the outcomes property.
     * 
     * @return
     *     possible object is
     *     {@link Outcomes }
     *     
     */
    public Outcomes getOutcomes() {
        return outcomes;
    }

    /**
     * Sets the value of the outcomes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outcomes }
     *     
     */
    public void setOutcomes(Outcomes value) {
        this.outcomes = value;
    }

    /**
     * Gets the value of the restrictedActions property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictedActions }
     *     
     */
    public RestrictedActions getRestrictedActions() {
        return restrictedActions;
    }

    /**
     * Sets the value of the restrictedActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictedActions }
     *     
     */
    public void setRestrictedActions(RestrictedActions value) {
        this.restrictedActions = value;
    }

    /**
     * Gets the value of the payload property.
     * 
     * @return
     *     possible object is
     *     {@link Payload }
     *     
     */
    public Payload getPayload() {
        return payload;
    }

    /**
     * Sets the value of the payload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payload }
     *     
     */
    public void setPayload(Payload value) {
        this.payload = value;
    }

    /**
     * Gets the value of the bpelEventListener property.
     * 
     */
    public boolean isBpelEventListener() {
        return bpelEventListener;
    }

    /**
     * Sets the value of the bpelEventListener property.
     * 
     */
    public void setBpelEventListener(boolean value) {
        this.bpelEventListener = value;
    }

    /**
     * Gets the value of the bpelNoCallbacks property.
     * 
     */
    public boolean isBpelNoCallbacks() {
        return bpelNoCallbacks;
    }

    /**
     * Sets the value of the bpelNoCallbacks property.
     * 
     */
    public void setBpelNoCallbacks(boolean value) {
        this.bpelNoCallbacks = value;
    }

    /**
     * Gets the value of the showCompleteGraphicalHistory property.
     * 
     */
    public boolean isShowCompleteGraphicalHistory() {
        return showCompleteGraphicalHistory;
    }

    /**
     * Sets the value of the showCompleteGraphicalHistory property.
     * 
     */
    public void setShowCompleteGraphicalHistory(boolean value) {
        this.showCompleteGraphicalHistory = value;
    }

    /**
     * Gets the value of the reevalTranslatablesOnUpdate property.
     * 
     */
    public boolean isReevalTranslatablesOnUpdate() {
        return reevalTranslatablesOnUpdate;
    }

    /**
     * Sets the value of the reevalTranslatablesOnUpdate property.
     * 
     */
    public void setReevalTranslatablesOnUpdate(boolean value) {
        this.reevalTranslatablesOnUpdate = value;
    }

    /**
     * Gets the value of the preActionMandatoryUserSteps property.
     * 
     * @return
     *     possible object is
     *     {@link PreActionMandatoryUserSteps }
     *     
     */
    public PreActionMandatoryUserSteps getPreActionMandatoryUserSteps() {
        return preActionMandatoryUserSteps;
    }

    /**
     * Sets the value of the preActionMandatoryUserSteps property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreActionMandatoryUserSteps }
     *     
     */
    public void setPreActionMandatoryUserSteps(PreActionMandatoryUserSteps value) {
        this.preActionMandatoryUserSteps = value;
    }

    /**
     * Gets the value of the allowInitiatorEditParticipants property.
     * 
     */
    public boolean isAllowInitiatorEditParticipants() {
        return allowInitiatorEditParticipants;
    }

    /**
     * Sets the value of the allowInitiatorEditParticipants property.
     * 
     */
    public void setAllowInitiatorEditParticipants(boolean value) {
        this.allowInitiatorEditParticipants = value;
    }

    /**
     * Gets the value of the allowParticipantsEditParticipants property.
     * 
     */
    public boolean isAllowParticipantsEditParticipants() {
        return allowParticipantsEditParticipants;
    }

    /**
     * Sets the value of the allowParticipantsEditParticipants property.
     * 
     */
    public void setAllowParticipantsEditParticipants(boolean value) {
        this.allowParticipantsEditParticipants = value;
    }

    /**
     * Gets the value of the globalCreationTask property.
     * 
     */
    public boolean isGlobalCreationTask() {
        return globalCreationTask;
    }

    /**
     * Sets the value of the globalCreationTask property.
     * 
     */
    public void setGlobalCreationTask(boolean value) {
        this.globalCreationTask = value;
    }

    /**
     * Gets the value of the taskFlowFileLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskFlowFileLocation() {
        return taskFlowFileLocation;
    }

    /**
     * Sets the value of the taskFlowFileLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskFlowFileLocation(String value) {
        this.taskFlowFileLocation = value;
    }

    /**
     * Gets the value of the workflowConditions property.
     * 
     * @return
     *     possible object is
     *     {@link WorkflowConditions }
     *     
     */
    public WorkflowConditions getWorkflowConditions() {
        return workflowConditions;
    }

    /**
     * Sets the value of the workflowConditions property.
     * 
     * @param value
     *     allowed object is
     *     {@link WorkflowConditions }
     *     
     */
    public void setWorkflowConditions(WorkflowConditions value) {
        this.workflowConditions = value;
    }

    /**
     * Gets the value of the taskSequenceTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the taskSequenceTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTaskSequenceTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTaskSequenceTypes() {
        if (taskSequenceTypes == null) {
            taskSequenceTypes = new ArrayList<String>();
        }
        return this.taskSequenceTypes;
    }

}
